# Config for running the InferenceRecipe in dev/generate_v2.py to generate output
# from a Llama4 17Bx16E MoE model
#
# To launch, run the following command from root torchtune directory:
#    tune run dev/generate_v2 --config llama4/17Bx16_generation_v2.yaml

# Model arguments
model:
  _component_: torchtune.models.llama4.llama4_17bx16e

# Transform arguments
tokenizer:
  _component_: torchtune.models.llama3.llama3_tokenizer
  path: /tmp/Llama-3.2-1B-Instruct/original/tokenizer.model
  max_seq_len: 8192

# Checkpointer
checkpointer:
  _component_: torchtune.training.FullModelMetaCheckpointer
  # loading large ckpt from local is much faster than loading from pci-wsf
  # the equivalent pci-wsf path: /home/<username>/pci-wsf/jessicazhong/checkpoints/17B_moe_text_mp1pp1_non_te/
  checkpoint_dir: /mnt/wsfuse/jessicazhong/checkpoints/17B_moe_svt_mp1pp1_feb_non_te
  checkpoint_files: [consolidated_with_vision_and_speech_encoder_weights.00.pth]
  recipe_checkpoint: null
  output_dir: /tmp/Llama-4-17B-MOE/
  model_type: LLAMA4

# Device
device: cuda
dtype: bf16
seed: 1234
log_level: INFO

# Generation arguments
prompt:
  system: You are a helpful assistant.
  user:
    text: How are you doing?
max_new_tokens: 200
temperature: 0.6 # 0.8 and 0.6 are popular values to try
top_k: 300
