name: Recipe Tests

on:
  push:
    branches: [ main ]
  pull_request:
  workflow_dispatch:


concurrency:
  group: recipe-test-${{ github.workflow }}-${{ github.ref == 'refs/heads/main' && github.run_number || github.ref }}
  cancel-in-progress: true

permissions:
  id-token: write
  contents: read

jobs:
  recipe_test:
    strategy:
      matrix:
        include:
          - name: CPU
            runs-on: linux.2xlarge
            gpu-arch-type: "cpu"
            gpu-arch-version: ""

    uses: pytorch/test-infra/.github/workflows/linux_job.yml@main
    with:
      timeout: 60
      runner: ${{ matrix.runs-on }}
      gpu-arch-type: ${{ matrix.gpu-arch-type }}
      gpu-arch-version: ${{ matrix.gpu-arch-version }}
      script: |
        conda create -n venv python=3.9 -y
        conda activate venv
        echo "::group::Install newer objcopy that supports --set-section-alignment"
        yum install -y  devtoolset-10-binutils
        export PATH=/opt/rh/devtoolset-10/root/usr/bin/:$PATH
        python -m pip install --upgrade pip
        python -m pip install torch torchvision torchao
        python -m pip install -e ".[dev]"
        python -m pip install lm-eval==0.4.*
        pytest test --verbose -s
        pytest tests -m integration_test --cov=. --cov-report=xml --durations=20 -vv
