name: Recipe Tests

on:
  push:
    branches: [ main ]
  pull_request:
  workflow_dispatch:


concurrency:
  group: recipe-test-${{ github.workflow }}-${{ github.ref == 'refs/heads/main' && github.run_number || github.ref }}
  cancel-in-progress: true

permissions:
  id-token: write
  contents: read

jobs:
  recipe_test:
    strategy:
      matrix:
        include:
          - name: CPU
            runs-on: linux.g5.12xlarge.nvidia.gpu
            gpu-arch-type: "cuda"
            gpu-arch-version: "12.1"

    uses: pytorch/test-infra/.github/workflows/linux_job.yml@main
    with:
      timeout: 60
      runner: ${{ matrix.runs-on }}
      gpu-arch-type: ${{ matrix.gpu-arch-type }}
      gpu-arch-version: ${{ matrix.gpu-arch-version }}
      # Python=3.10 for now cause bitsandbytes?
      # also for some reason pip install -e ".[dev]" doesn't work?
      script: |
        conda create -n venv python=3.10 -y
        conda activate venv
        yum install -y  devtoolset-10-binutils
        export PATH=/opt/rh/devtoolset-10/root/usr/bin/:$PATH
        python -m pip install --upgrade pip
        pip install torch torchvision torchao
        pip install .
        pip install lm-eval==0.4.* bitsandbytes>=0.43.0 comet_ml>=3.44.2 pre-commit pytest==7.4.0 pytest-cov pytest-mock pytest-integration tensorboard wandb expecttest
        pytest tests -m integration_test --cov=. --cov-report=xml --durations=20 -vv
